all:
    hosts:
        deploy-local.pcarpus.de:
        build-system.pcarpus.de:
        testing1.pcarpus.de:
        testing2.pcarpus.de:
    children:
        firewalled_system:
            hosts:
                deploy-local.pcarpus.de:
                build-system.pcarpus.de:
                testing1.pcarpus.de:
                testing2.pcarpus.de:
        testsystem:
            hosts:
                testing1.pcarpus.de:
                testing2.pcarpus.de:
        build-system:
            hosts:
                build-system.pcarpus.de:
        deploy-system:
            hosts:
                deploy-local.pcarpus.de:


